# Generated by Django 4.1 on 2022-09-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sage', models.IntegerField()),
                ('saddr', models.CharField(max_length=20)),
                ('m1', models.IntegerField()),
                ('m2', models.IntegerField()),
            ],
        ),
    ]
