# Generated by Django 4.1 on 2022-10-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nthinstituteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('courses', models.CharField(max_length=50)),
                ('referred_by', models.CharField(max_length=50)),
            ],
        ),
    ]
